config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :inquiries, only: [:new, :create]
  get "/inquiries/done", to: "inquiries#done"

  # 社員
  devise_for :employees,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者
  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 社員
  scope module: :public do
    resources :genres, only: [:index,:show]
    resources :addresses, only: [:index,:show]
    resources :items, only: [:index]
    resources :works, only: [:index,:show] do
      resources :work_comments, only:[:create,:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show]
  end

  # 管理者
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :addresses, only: [:index,:show,:new,:edit,:create,:update,:destroy]
    resources :items, only: [:index,:edit,:create,:update,:destroy]
    resources :works, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :work_comments, only:[:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update,:destroy]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show, :destroy]
    end

end

app/models/address.rb
class Address < ApplicationRecord
  has_many :works, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true, uniqueness: { scope: :genre.name }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def work_address_name
    genre.name + '  ' + name
  end

  def self.search_for(content)
    Address.where('name LIKE ?', '%' + content + '%')
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name,presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :employee_number, presence: true, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_comments, dependent: :destroy

   validates :last_name, presence: true
   validates :first_name,presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :employee_number, presence: true, uniqueness: true
   validates :phone_number,presence: true
   validates :car_number, presence: true


  def employee_name
    last_name + first_name
  end


  # ゲストログイン用メソッド
  GUEST_EMPLOYEE_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_EMPLOYEE_EMAIL) do |employee|
      employee.password = SecureRandom.urlsafe_base64
      employee.last_name = "ゲスト"
      employee.first_name = "ユーザ"
      employee.last_name_kana = "ゲスト"
      employee.first_name_kana = "ユーザ"
      employee.employee_number = "9999"
      employee.phone_number = "99999999999"
      employee.car_number = "9999"
    end
  end

  def guest_employee?
    email == GUEST_EMPLOYEE_EMAIL
  end


  def self.search_for(content)
    #Employee.where('last_name || first_name LIKE ?', '%' + content + '%')
    Employee.where('last_name LIKE ?', '%' + content + '%').or(Employee.where('first_name LIKE ?', '%' + content + '%'))
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :color }

  # カラー赤:0, 青:1, 黄:2, 緑:3, 紫:4, 橙:5
  enum color: { salmon:0, deepskyblue:1, yellow:2, greenyellow:3, violet:4, coral:5 }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :works, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :admin
  belongs_to :employee
  belongs_to :item
  belongs_to :address
  has_many :work_comments, dependent: :destroy

  validates :address_id, presence: true
  validates :item_id,presence: true
  validates :admin_id, presence: true
  validates :employee_id, presence: true

  validates :date, presence: true
  validates :start_time, presence: true, uniqueness: {scope: [:date, :employee_id]}
  validates :end_time, presence: true
  validates :amount, presence: true

  def self.search_for(content)
    Work.joins(:address).where('addresses.name LIKE ?', '%' + content + '%')
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :work
  belongs_to :employee

  validates :body, presence: true

end

app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @inquiries = Inquiry.all.sort.reverse
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy
    redirect_to admin_inquiries_path
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      @items = Item.all
      render :index
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      @items = Item.all
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end


  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :genre_all, except: :destroy

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name, :first_name, :last_name_kana, :first_name_kana, :employee_number, :phone_number, :car_number])
  end

  def genre_all
    @genres = Genre.all
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.score = Language.get_data(inquiry_params[:message])
    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to inquiries_done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :subject, :message)
  end
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/progresses_helper.rb
module Admin::ProgressesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/admin/inquiries/_sentiment_score.html.erb
<!--AI評価点数-->
<span class="sentiment-score">
  <!--マイナスの場合は赤-->
  <% if inquiry.score < 0 %>
    <strong style="color: red;"><%= inquiry.score %></strong>
  <!--0の場合は黒-->
  <% elsif inquiry.score == 0 %>
    <%= inquiry.score %>
  <!--プラスの場合は緑-->
  <% else %>
    <strong style="color: green;"><%= inquiry.score %></strong>
  <% end %>
</span>

app/views/admin/inquiries/index.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <!--問い合わせ一覧-->
    <div class="col-10">
      <h1>問い合わせ一覧</h1>
        <div class="inquiry_index">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>お問い合わせ日</th>
                <th>件名</th>
                <th>名前</th>
                <th>評価点数</th>
              </tr>
            </thead>
            <tbody>
              <% @inquiries.each do |inquiry| %>
                <tr>
                  <td><%= l inquiry.created_at, format: :time %></td>
                  <td>
                    <%= link_to admin_inquiry_path(inquiry.id) do %>
                      <%= inquiry.subject %>
                    <% end %>
                  </td>
                  <td><%= inquiry.name %></td>
                  <td>
                    <!--AI評価点数-->
                    <%= render 'admin/inquiries/sentiment_score', inquiry: inquiry %>
                  </td>
                </tr>
              <% end %>

            </tbody>
         </table>
       </div>
    </div>
  </div>
</div>

app/views/admin/inquiries/show.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <!--問い合わせ詳細-->
    <div class="col-10">
      <h1>問い合わせ詳細</h1>
        <div class="inquiry_index">
          <table class="table table-borderless">
            <tr>
              <td>お問い合わせ日</td>
              <td><%= l @inquiry.created_at, format: :time %></td>
            </tr>
            <tr>
              <td>名前</td>
              <td><%= @inquiry.name %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= @inquiry.email %></td>
            </tr>
            <tr>
              <td>評価点数</td>
              <td>
                <!--AI評価点数-->
                <%= render 'admin/inquiries/sentiment_score', inquiry: @inquiry %>
              </td>
            </tr>
            <tr>
              <td>件名</td>
              <td><%= @inquiry.subject %></td>
            </tr>
            <tr>
              <td>内容</td>
              <td><%= @inquiry.message %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= link_to "削除", admin_inquiry_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %></td>
            </tr>
         </table>
       </div>
    </div>
  </div>
</div>

app/views/inquiries/done.html.erb
<div class="container pt-5">
  <h1 class="text-center">お問い合わせを送信しました</h1>
  <p class="text-center" style="margin-top: 40px;">
    <%= link_to "こちらを押してください", root_path %>
  </p>
</div>

app/views/inquiries/new.html.erb
<div class="container-fluid light-blue-container p-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">

      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @inquiry %>

      <%= form_with model: @inquiry do |f| %>
        <div class="form-group">
          <%= f.label :name, 'お名前' %><span class="text-danger">*</span>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %><span class="text-danger">*</span>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :subject, '件名' %><span class="text-danger">*</span>
          <%= f.text_area :subject, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :message, 'メッセージ' %><span class="text-danger">*</span>
          <%= f.text_area :message, size: '10x10', class: 'form-control' %>
        </div>

        <div>
          <%= f.submit '送信', class: "btn btn-outline-info" %>
        </div>
      <% end %>

    </div>
  </div>
</div>