config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :inquiries, only: [:new, :create]
  get "/inquiries/done", to: "inquiries#done"

  # 社員
  devise_for :employees,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者
  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 社員
  scope module: :public do
    resources :genres, only: [:index,:show]
    resources :addresses, only: [:index,:show]
    resources :items, only: [:index]
    resources :works, only: [:index,:show] do
      resources :work_comments, only:[:create,:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show]
  end

  # 管理者
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :addresses, only: [:index,:show,:new,:edit,:create,:update,:destroy]
    resources :items, only: [:index,:edit,:create,:update,:destroy]
    resources :works, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :work_comments, only:[:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update,:destroy]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show, :destroy]
    end

end

app/models/address.rb
class Address < ApplicationRecord
  has_many :works, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true, uniqueness: { scope: :genre.name }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def work_address_name
    genre.name + '  ' + name
  end

  def self.search_for(content)
    Address.where('name LIKE ?', '%' + content + '%')
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name,presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :employee_number, presence: true, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_comments, dependent: :destroy

   validates :last_name, presence: true
   validates :first_name,presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :employee_number, presence: true, uniqueness: true
   validates :phone_number,presence: true
   validates :car_number, presence: true


  def employee_name
    last_name + first_name
  end


  # ゲストログイン用メソッド
  GUEST_EMPLOYEE_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_EMPLOYEE_EMAIL) do |employee|
      employee.password = SecureRandom.urlsafe_base64
      employee.last_name = "ゲスト"
      employee.first_name = "ユーザ"
      employee.last_name_kana = "ゲスト"
      employee.first_name_kana = "ユーザ"
      employee.employee_number = "9999"
      employee.phone_number = "99999999999"
      employee.car_number = "9999"
    end
  end

  def guest_employee?
    email == GUEST_EMPLOYEE_EMAIL
  end


  def self.search_for(content)
    #Employee.where('last_name || first_name LIKE ?', '%' + content + '%')
    Employee.where('last_name LIKE ?', '%' + content + '%').or(Employee.where('first_name LIKE ?', '%' + content + '%'))
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :color }

  # カラー赤:0, 青:1, 黄:2, 緑:3, 紫:4, 橙:5
  enum color: { salmon:0, deepskyblue:1, yellow:2, greenyellow:3, violet:4, coral:5 }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :works, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :admin
  belongs_to :employee
  belongs_to :item
  belongs_to :address
  has_many :work_comments, dependent: :destroy

  validates :address_id, presence: true
  validates :item_id,presence: true
  validates :admin_id, presence: true
  validates :employee_id, presence: true

  validates :date, presence: true
  validates :start_time, presence: true, uniqueness: {scope: [:date, :employee_id]}
  validates :end_time, presence: true
  validates :amount, presence: true

  def self.search_for(content)
    Work.joins(:address).where('addresses.name LIKE ?', '%' + content + '%')
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :work
  belongs_to :employee

  validates :body, presence: true

end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @addresses = Address.all.order(:genre_id)
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to admin_addresses_path
    else
      render :new
    end
  end

  def show
    @address = Address.find(params[:id])
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to admin_address_path
    else
      render :edit
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to admin_addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:genre_id, :name, :postal_code, :address, :phone_number)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :genre_all, except: :destroy

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name, :first_name, :last_name_kana, :first_name_kana, :employee_number, :phone_number, :car_number])
  end

  def genre_all
    @genres = Genre.all
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.score = Language.get_data(inquiry_params[:message])
    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to inquiries_done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :subject, :message)
  end
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/admin/addresses/_index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>ジャンル</th>
      <th>店舗名</th>
      <th>電話番号</th>
      <th>郵便番号</th>
      <th>住所</th>
    </tr>
  </thead>
  <tbody>
    <% addresses.each do |address| %>
        <tr>
          <td><%= address.genre.name %></td>
          <td>
            <%= link_to admin_address_path(address.id) do %>
              <%= address.name %>
            <% end %>
          </td>
          <td><%= address.phone_number %></td>
          <td><%= address.postal_code %></td>
          <td><%= address.address %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/addresses/edit.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <div class="col-10">
      <h1>配送先編集</h1>
      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @address %>

        <div class="address_edit">
          <%= form_with model: @address, url: admin_address_path do |f| %>
            <table class="table table-borderless">
              <tr>
                <td>ジャンル</td>
                <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name, @address.genre_id) %></td>
              </tr>
              <tr>
                <td>店舗名</td>
                <td><%= f.text_field :name %></td>
              </tr>
              <tr>
                <td>電話番号</td>
                <td><%= f.text_field :phone_number %></td>
              </tr>
              <tr>
                <td>郵便番号(ハイフンなし)</td>
                <td><%= f.text_field :postal_code %></td>
              </tr>
              <tr>
                <td>住所</td>
                <td><%= f.text_field :address %></td>
              </tr>
              <tr>
                <td></td>
                <td><%= f.submit "変更を保存", class: "btn btn-primary" %></td>
              </tr>
            </table>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/admin/addresses/index.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <div class="col-10">
      <h1>配送先一覧</h1>
        <!--配送先追加機能-->
        <div class="address_new">
          <%= link_to new_admin_address_path do %>
            <button type="button" class="btn btn page-link text-dark d-inline-block">配送先追加</button>
          <% end %>
        </div>

        <!--配送先一覧-->
        <div class="address_list">
          <%= render 'admin/addresses/index', addresses: @addresses %>
        </div>
    </div>
  </div>
</div>

app/views/admin/addresses/new.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <div class="col-10">
      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @address %>

      <h1>配送先登録</h1>
        <div class="address_new">
          <%= form_with model: @address, url: admin_addresses_path do |f| %>
            <table class="table table-borderless">
              <tr>
                <td>ジャンル</td>
                <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
              </tr>
              <tr>
                <td>店舗名</td>
                <td><%= f.text_field :name %></td>
              </tr>
              <tr>
                <td>電話番号</td>
                <td><%= f.text_field :phone_number %></td>
              </tr>
              <tr>
                <td>郵便番号(ハイフンなし)</td>
                <td><%= f.text_field :postal_code %></td>
              </tr>
              <tr>
                <td>住所</td>
                <td><%= f.text_field :address %></td>
              </tr>
              <tr>
                <td></td>
                <td><%= f.submit "新規登録", class: "btn btn-primary" %></td>
              </tr>
            </table>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/admin/addresses/show.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <div class="col-10">
      <h1>配送先詳細</h1>
        <div class="address_information">
          <table class="table table-borderless">
            <tr>
              <td>ジャンル</td>
              <td><%= @address.genre.name %></td>
            </tr>
            <tr>
              <td>店舗名</td>
              <td><%= @address.name %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= @address.phone_number %></td>
            </tr>
            <tr>
              <td>郵便番号(ハイフンなし)</td>
              <td><%= @address.postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= @address.address %></td>
            </tr>
            <tr>
              <td></td>
              <td>
                <%= link_to "編集", edit_admin_address_path, class: "btn btn-primary" %>
                <%= link_to "削除", admin_address_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
              </td>
            </tr>
          </table>
        </div>
    </div>
  </div>
</div>