config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :inquiries, only: [:new, :create]
  get "/inquiries/done", to: "inquiries#done"

  # 社員
  devise_for :employees,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者
  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 社員
  scope module: :public do
    resources :genres, only: [:index,:show]
    resources :addresses, only: [:index,:show]
    resources :items, only: [:index]
    resources :works, only: [:index,:show] do
      resources :work_comments, only:[:create,:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show]
  end

  # 管理者
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :addresses, only: [:index,:show,:new,:edit,:create,:update,:destroy]
    resources :items, only: [:index,:edit,:create,:update,:destroy]
    resources :works, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :work_comments, only:[:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update,:destroy]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show, :destroy]
    end

end

app/models/address.rb
class Address < ApplicationRecord
  has_many :works, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true, uniqueness: { scope: :genre.name }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def work_address_name
    genre.name + '  ' + name
  end

  def self.search_for(content)
    Address.where('name LIKE ?', '%' + content + '%')
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name,presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :employee_number, presence: true, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_comments, dependent: :destroy

   validates :last_name, presence: true
   validates :first_name,presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :employee_number, presence: true, uniqueness: true
   validates :phone_number,presence: true
   validates :car_number, presence: true


  def employee_name
    last_name + first_name
  end


  # ゲストログイン用メソッド
  GUEST_EMPLOYEE_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_EMPLOYEE_EMAIL) do |employee|
      employee.password = SecureRandom.urlsafe_base64
      employee.last_name = "ゲスト"
      employee.first_name = "ユーザ"
      employee.last_name_kana = "ゲスト"
      employee.first_name_kana = "ユーザ"
      employee.employee_number = "9999"
      employee.phone_number = "99999999999"
      employee.car_number = "9999"
    end
  end

  def guest_employee?
    email == GUEST_EMPLOYEE_EMAIL
  end


  def self.search_for(content)
    #Employee.where('last_name || first_name LIKE ?', '%' + content + '%')
    Employee.where('last_name LIKE ?', '%' + content + '%').or(Employee.where('first_name LIKE ?', '%' + content + '%'))
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :color }

  # カラー赤:0, 青:1, 黄:2, 緑:3, 紫:4, 橙:5
  enum color: { salmon:0, deepskyblue:1, yellow:2, greenyellow:3, violet:4, coral:5 }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :works, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :admin
  belongs_to :employee
  belongs_to :item
  belongs_to :address
  has_many :work_comments, dependent: :destroy

  validates :address_id, presence: true
  validates :item_id,presence: true
  validates :admin_id, presence: true
  validates :employee_id, presence: true

  validates :date, presence: true
  validates :start_time, presence: true, uniqueness: {scope: [:date, :employee_id]}
  validates :end_time, presence: true
  validates :amount, presence: true

  def self.search_for(content)
    Work.joins(:address).where('addresses.name LIKE ?', '%' + content + '%')
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :work
  belongs_to :employee

  validates :body, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def show
    @genre = Genre.find(params[:id])
    @works = Work.all.order(:date)

  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :color)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :genre_all, except: :destroy

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name, :first_name, :last_name_kana, :first_name_kana, :employee_number, :phone_number, :car_number])
  end

  def genre_all
    @genres = Genre.all
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.score = Language.get_data(inquiry_params[:message])
    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to inquiries_done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :subject, :message)
  end
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/admin/genres/_genre.html.erb
<!--ジャンル検索-->
<div class="genre_search">
  <% genres.each do |genre| %>
    <table class="table table-borderless table-sm table-hover">
      <tr>
        <td>
          <%= link_to admin_genre_path(genre.id), style: "text-decoration: none;" do %>
            <div style="color: black;"><%= genre.name %></div>
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'genre', genres: @genres %>
    </div>

    <div class="col-10">

      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @genre %>

      <h1>ジャンル編集</h1>
        <div class="genre_edit">
          <%= form_with model: @genre, url: admin_genre_path do |f| %>
            <p>
              ジャンル名
              <%= f.text_field :name %>
            </p>
            <p>
              カラー
              <%= f.select :color, Genre.colors.keys.map { |key| [I18n.t("enums.genre.color.#{key}"), key] } %>
            </p>
            <%= f.submit "変更内容を保存" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'genre', genres: @genres %>
    </div>

    <div class="col-10">

      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @genre %>

      <h1>ジャンル一覧・登録</h1>
        <!--登録-->
        <div class="genre_new">
          <%= form_with model: @genre, url: admin_genres_path do |f| %>
            <p>
              ジャンル名
              <%= f.text_field :name %>
            </p>
            <p>
              カラー

              <%= f.select :color, Genre.colors.keys.map { |key| [I18n.t("enums.genre.color.#{key}"), key] } %>
            </p>
            <%= f.submit "ジャンル登録" %>
          <% end %>
        </div>

        <!--一覧-->
        <div class="genre_table">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>ジャンル名</th>
                <th>カラー</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @genres.each do |genre| %>
                <tr>
                  <td><%= genre.name %></td>
                  <td><%= genre.color_i18n %></td>
                  <td>
                    <%= link_to "編集", edit_admin_genre_path(genre), class: "btn btn-primary" %>
                    <%= link_to "削除", admin_genre_path(genre.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>
</div>

app/views/admin/genres/show.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'genre', genres: @genres %>
    </div>

    <div class="col-10">
      <h1>ジャンル検索結果一覧</h1>
        <div><h3><%= @genre.name %></h3></div>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>日付</th>
              <th>店舗名</th>
              <th>担当者</th>
              <th>配送状況</th>
            </tr>
          </thead>
          <tbody>
            <% @works.each do |work| %>
              <% if @genre.id == work.address.genre_id %>
                <tr>
                  <td>
                    <%= link_to admin_work_path(work.id) do %>
                      <%= l work.date %>
                    <% end %>
                  </td>
                  <td><%= work.address.name %></td>
                  <td><%= work.employee.employee_name %></td>
                  <td><%= render 'admin/works/work_status', work: work %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>