config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :inquiries, only: [:new, :create]
  get "/inquiries/done", to: "inquiries#done"

  # 社員
  devise_for :employees,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者
  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :employee do
    post "employees/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 社員
  scope module: :public do
    resources :genres, only: [:index,:show]
    resources :addresses, only: [:index,:show]
    resources :items, only: [:index]
    resources :works, only: [:index,:show] do
      resources :work_comments, only:[:create,:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show]
  end

  # 管理者
  namespace :admin do
    resources :genres, only: [:index,:show,:edit,:create,:update, :destroy]
    resources :addresses, only: [:index,:show,:new,:edit,:create,:update,:destroy]
    resources :items, only: [:index,:edit,:create,:update,:destroy]
    resources :works, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
      resources :work_comments, only:[:destroy]
    end
    patch "works/:id/status" => "works#status", as: 'works_status'
    resources :employees, only:[:index,:show,:edit,:update,:destroy]
    resources :progresses, only:[:index]
    get "/searches", to: "searches#search"
    resources :inquiries, only: [:index, :show, :destroy]
    end

end

app/models/address.rb
class Address < ApplicationRecord
  has_many :works, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true, uniqueness: { scope: :genre.name }
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def work_address_name
    genre.name + '  ' + name
  end

  def self.search_for(content)
    Address.where('name LIKE ?', '%' + content + '%')
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name,presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :employee_number, presence: true, uniqueness: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works, dependent: :destroy
  has_many :work_comments, dependent: :destroy

   validates :last_name, presence: true
   validates :first_name,presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :employee_number, presence: true, uniqueness: true
   validates :phone_number,presence: true
   validates :car_number, presence: true


  def employee_name
    last_name + first_name
  end


  # ゲストログイン用メソッド
  GUEST_EMPLOYEE_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_EMPLOYEE_EMAIL) do |employee|
      employee.password = SecureRandom.urlsafe_base64
      employee.last_name = "ゲスト"
      employee.first_name = "ユーザ"
      employee.last_name_kana = "ゲスト"
      employee.first_name_kana = "ユーザ"
      employee.employee_number = "9999"
      employee.phone_number = "99999999999"
      employee.car_number = "9999"
    end
  end

  def guest_employee?
    email == GUEST_EMPLOYEE_EMAIL
  end


  def self.search_for(content)
    #Employee.where('last_name || first_name LIKE ?', '%' + content + '%')
    Employee.where('last_name LIKE ?', '%' + content + '%').or(Employee.where('first_name LIKE ?', '%' + content + '%'))
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :color }

  # カラー赤:0, 青:1, 黄:2, 緑:3, 紫:4, 橙:5
  enum color: { salmon:0, deepskyblue:1, yellow:2, greenyellow:3, violet:4, coral:5 }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :works, dependent: :destroy

  validates :name, presence: true, uniqueness: true

end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :admin
  belongs_to :employee
  belongs_to :item
  belongs_to :address
  has_many :work_comments, dependent: :destroy

  validates :address_id, presence: true
  validates :item_id,presence: true
  validates :admin_id, presence: true
  validates :employee_id, presence: true

  validates :date, presence: true
  validates :start_time, presence: true, uniqueness: {scope: [:date, :employee_id]}
  validates :end_time, presence: true
  validates :amount, presence: true

  def self.search_for(content)
    Work.joins(:address).where('addresses.name LIKE ?', '%' + content + '%')
  end

end

app/models/work_comment.rb
class WorkComment < ApplicationRecord
  belongs_to :work
  belongs_to :employee

  validates :body, presence: true

end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController
  before_action :authenticate_admin!

  def index
    @works = Work.all.order(:date)
    @employees = Employee.all
    @work_list = {}
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to admin_works_path
    else
      render :new
    end

  end

  def status
    @work = Work.find(params[:id])
    if @work.status == true
      @work.update_attribute(:status, false)
    else
      @work.update_attribute(:status, true)
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to admin_work_path
    else
      render :edit
    end
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to admin_works_path
  end

  private

  def work_params
    params.require(:work).permit(:address_id, :item_id, :admin_id, :employee_id, :date, :start_time, :end_time, :amount, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :genre_all, except: :destroy

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name, :first_name, :last_name_kana, :first_name_kana, :employee_number, :phone_number, :car_number])
  end

  def genre_all
    @genres = Genre.all
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.score = Language.get_data(inquiry_params[:message])
    if @inquiry.save
      InquiryMailer.send_mail(@inquiry).deliver_now
      redirect_to inquiries_done_path
    else
      render :new
    end
  end

  def done
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :subject, :message)
  end
end

app/helpers/admin/addresses_helper.rb
module Admin::AddressesHelper
end

app/helpers/admin/employees_helper.rb
module Admin::EmployeesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/admin/works/_work_status.html.erb
<!--配送状況-->
<div id ="work_status_<%= work.id %>">
  <% if  work.status %>
    <%= link_to admin_works_status_path(work.id), method: :patch, remote: true, data: {"turbolinks" => false}, style: "text-decoration: none;" do %>
      <strong style="color: red;" >配送未達</strong>
    <% end %>

  <% else %>
    <%= link_to admin_works_status_path(work.id), method: :patch, remote: true, data: {"turbolinks" => false}, style: "text-decoration: none;" do %>
      <strong style="color: green;" >配送完了</strong>
    <% end %>
  <% end %>
</div>

app/views/admin/works/edit.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <div class="col-10">
      <h1>仕事編集</h1>

      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @work %>

        <%= form_with model: @work, url: admin_work_path do |f| %>
          <table class="table table-borderless">
            <!--管理者ID-->
            <%= f.hidden_field :admin_id, :value => current_admin.id %>
            <tr>
              <td>店舗名</td>
              <td><%= f.select :address_id, options_from_collection_for_select(Address.all.order(:genre_id), :id, :work_address_name, @work.address_id) %></td>
            </tr>
            <tr>
              <td>日付</td>
              <td><%= f.date_field :date, min: Time.zone.now, class: "h-12 rounded-[3px] text-[#333333] font-bold invalid:text-line-200" %></td>
            </tr>
            <tr>
              <td>開始時間</td>
              <td><%= f.time_field :start_time %></td>
            </tr>
            <tr>
              <td>終了時間</td>
              <td><%= f.time_field :end_time %></td>
            </tr>
            <tr>
              <td>商品</td>
              <td>
                <%= f.select :item_id, options_from_collection_for_select(Item.all, :id, :name, @work.item_id) %>
                <%= f.select :amount, *[1..20] %>
              </td>
            </tr>
            <tr>
              <td>担当者</td>
              <td><%= f.select :employee_id, options_from_collection_for_select(Employee.all, :id, :employee_name, @work.employee_id) %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存する", class: "btn btn-primary" %></td>
            </tr>
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/works/index.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-1">
      <div class="d-flex">
        <% @genres.each do |genre| %>
          <%= link_to admin_genre_path(genre.id), style: "text-decoration: none;" do %>
            <button type="button" class="btn page-link text-dark d-inline-block"><div style="color: black; width:3rem;height:1rem;"><%= genre.name %></div></button>
          <% end %>
        <% end %>
      </div>
    </div>

    <!--配送先登録-->
    <div class="col offset-10">
      <%= link_to new_admin_work_path do %>
        <button type="button" class="btn btn-outline-dark rounded-circle p-0" style="width:2rem;height:2rem;" >+</button>
      <% end %>
    </div>
  </div>

  <!--予定表-->
  <div class="row">
        <%
          # work_list = {}
        %>
        <% Employee.all.each do |employee|%>

          <% employee.works.each do |work| %>

            <%
              if @work_list.include?(work.date)
                # なにもしない
              else
                # 日付の入れ物を作る
                @work_list[work.date] = {}
              end

              if @work_list[work.date].include?(employee.id)
                # なにもしない
              else
                # 同じ日付のユーザーの入れ物を作る
                @work_list[work.date][employee.id] = []
              end

              # 同じユーザーの仕事を含める
              @work_list[work.date][employee.id].push(
                work
              )
            %>
          <% end %>
        <% end %>

        <%
          # 日付順に並び替え
          @work_list = @work_list.sort
        %>

        <% @work_list.each do |target_date, target_employee_id_list| %>

        <%
          # TODO これが通るなら出来る 社員のページネーション
          #page_target_employee_id_list = Kaminari.paginate_array(target_employee_id_list).page(params[:page]).per(5)

        %>
        <%#= paginate page_target_employee_id_list %>

          <h2><%= target_date %></h2>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th></th>
                  <th>9:00</th>
                  <th>10:00</th>
                  <th>11:00</th>
                  <th>12:00</th>
                  <th>13:00</th>
                  <th>14:00</th>
                  <th>15:00</th>
                  <th>16:00</th>
                  <th>17:00</th>
                  <th>18:00</th>
                </tr>
              </thead>
              <tbody>

            <% target_employee_id_list.each do |target_employee_id, target_work_list| %>

              <%
                # ユーザーの特定
                target_employee = Employee.find(target_employee_id)
              %>


                <tr>

                  <td>
                    <%= target_employee.last_name %><%= target_employee.first_name %></br>
                    <%= target_employee.car_number %> <br>
                  </td>

                  <% [*9..18].each do |num| %>


                    <%
                      not_work_flg = true # true なら未定
                    %>

                    <td>
                      <% target_work_list.each do |work| %>

                        <%
                          if work.start_time.strftime("%H").to_i == num || # 開始時刻と一致しているか？
                             ( work.start_time.strftime("%H").to_i < num && work.end_time.strftime("%H").to_i > num ) # 開始時刻よりも大きく尚且つ、終了時刻よりも前か？
                        %>
                          <span style="background-color: <%= work.address.genre.color %>">
                            <%= work.address.genre.name %></br>
                            <%= link_to admin_work_path(work.id), style: "color: black;" do %>
                              <%= work.address.name %></br>
                            <% end %>
                            <%= render 'admin/works/work_status', work: work %>
                          </span>
                          コメント<%= work.work_comments.count %>
                          <%
                            # 予定があるので未定ではない
                            not_work_flg = false
                          %>
                        <% end %>
                      <% end %>

                      <% if not_work_flg %>
                        未定
                      <% end %>
                    </td>

                  <% end %>

                <% end %>
              </tr>
            </tbody>
          </table>
        <% end %>
  </div>

</div>

app/views/admin/works/new.html.erb
<div class="container">
  <div class="row">

    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <div class="col-10">

      <!--エラーメッセージ-->
      <%= render 'layouts/errors', obj: @work %>

      <h1>仕事登録</h1>
        <%= form_with model: @work, url: admin_works_path do |f| %>
          <table class="table table-borderless">
            <!--管理者ID-->
            <%= f.hidden_field :admin_id, :value => current_admin.id %>
            <!--配送状況-->
            <%= f.hidden_field :status %>
            <tr>
              <td>店舗名</td>
              <td><%= f.select :address_id, options_from_collection_for_select(Address.all.order(:genre_id), :id, :work_address_name) %></td>
            </tr>
            <tr>
              <td>日付</td>
              <td><%= f.date_field :date, min: Time.zone.now, class: "h-12 rounded-[3px] text-[#333333] font-bold invalid:text-line-200" %></td>
            </tr>
            <tr>
              <td>開始時間</td>
              <td><%= f.time_field :start_time %></td>
            </tr>
            <tr>
              <td>終了時間</td>
              <td><%= f.time_field :end_time %></td>
            </tr>
            <tr>
              <td>商品</td>
              <td>
                <%= f.select :item_id, options_from_collection_for_select(Item.all, :id, :name) %>
                <%= f.select :amount, *[1..20] %>
              </td>
            </tr>
            <tr>
              <td>担当者</td>
              <td><%= f.select :employee_id, options_from_collection_for_select(Employee.all, :id, :employee_name) %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "新規登録", class: "btn btn-primary" %></td>
            </tr>
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/works/show.html.erb
<div class="container">

  <div class="row">
    <!--ジャンル検索-->
    <div class="col-2">
      <%= render 'admin/genres/genre', genres: @genres %>
    </div>

    <!--仕事詳細-->
    <div class="col-10">
      <h1>仕事詳細</h1>
        <div class="work_information">
          <table class="table table-borderless">
            <tr>
              <td>ジャンル</td>
              <td><%= @work.address.genre.name %></td>
            </tr>
            <tr>
              <td>店舗名</td>
              <td><%= @work.address.name %></td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= @work.address.postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= @work.address.address %></td>
            </tr>
            <tr>
              <td>日付</td>
              <td><%= l @work.date %></td>
            </tr>
            <tr>
              <td>開始時間</td>
              <td><%= l @work.start_time %></td>
            </tr>
            <tr>
              <td>終了時間</td>
              <td><%= l @work.end_time %></td>
            </tr>
            <tr>
              <td>商品</td>
              <td><%= @work.item.name %></td>
              <td><%= @work.amount %>　ケース</td>
            </tr>
            <tr>
              <td>担当者</td>
              <td><%= @work.employee.last_name %><%= @work.employee.first_name %></td>
            </tr>
            <tr>
              <td>配送状況</td>
              <td>
                <%= render 'admin/works/work_status', work: @work %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>
                <%= link_to "編集", edit_admin_work_path, class: "btn btn-primary" %>
                <%= link_to "削除", admin_work_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
              </td>
            </tr>
          </table>
        </div>
    </div>
  </div>

<!--コメント機能-->
  <div class="row">
    <div class="col-10 offset-2">
      <p>コメント件数:<span id = "comment_count"><%= @work.work_comments.count %></span></p>
        <%= render 'admin/work_comments/comment_list', work: @work, work_comment: @work_comment %>
    </div>

  </div>
</div>

app/views/admin/works/status.js.erb
$("#work_status_<%= @work.id %>").html("<%= j(render 'admin/works/work_status', work: @work) %>");